# This is a basic workflow to help you get started with Actions

name: Refresh URLhaus List

# Controls when the workflow will run
on:
  schedule:
    - cron: "10 10 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Fetch data and save to CSV
        run: curl https://urlhaus.abuse.ch/downloads/csv_recent/ > urlhaus_recent_list_with_header.csv      
      - name: Remove commented-out lines from the CSV
        run: grep -E '(^[^#\s])' urlhaus_recent_list_with_header.csv > urlhaus_recent_list.csv

      # Runs a set of commands using the runners shell
      - name: Head the CSV to confirm
        run: echo -e 'urlhaus_recent_list.csv -->' && head urlhaus_recent_list.csv
        
      - name: Commit files # commit the output folder
        run: |
              git config --local user.email "test@github.com"
              git config --local user.name "GitHub Action test"
              git add ./urlhaus_recent_list.csv
              git commit -m "Add changes"
              
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
